apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
name: spring-deployment
spec:
selector:
matchLabels:
app: spring
replicas: 3 # tells deployment to run 2 pods matching the template
template:
metadata:
labels:
app: spring
spec:
containers:
- name: spring
image: rachanathota/spring-boot-backend
ports:
- containerPort: 8080