apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring
  name: spring-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - image: rachanathota/spring-boot-backend:latest
        name: spring
