apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring
  name: spring-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring
  type: LoadBalancer